version: '2'
services:
  master:
    build: .
    container_name: master
    ports:
      - "8080:8080"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
  slave:
    build: .
    depends_on:
      - master
    command: /opt/spark/sbin/start-slave.sh spark://master:7077